apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: fuse-artemis-test-mzop
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: fuse-artemis-test-mzop
    app.kubernetes.io/part-of: artemis
  name: fuse-artemis-test-mzop
  namespace: burrzinga-tenant
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: fuse-artemis-test-mzop
    weight: null
status: {}
